categories: 
  - Tool Dependency Packages
description: "Contains a tool dependency definition that downloads and compiles version 1.10.0 of python six package"
name: package_python_2_7_six_1_10_0
owner: bebatut
remote_repository_url: https://github.com/ASaiM/galaxytools/tree/master/packages/package_python_2_7_six_1_10_0
