categories: [Tool Dependency Packages]
description: 'RDPTols is an open source command-line tool suite for performing a complete
  workflow of analysis tasks of NGS data.. '
homepage_url: https://github.com/rdpstaff/RDPTools
name: package_rdptools_2_0_2
owner: bebatut
remote_repository_url: https://github.com/ASaiM/galaxytools/tree/master/packages/package_rdptools_2_0_2
