categories: 
  - Metagenomics
description: Group humann2 uniref50 abundances to Gene Ontology (GO) slim terms
name: group_humann2_uniref_abundances_to_go
owner: bebatut
homepage_url: https://github.com/ASaiM/group_humann2_uniref_abundances_to_GO
remote_repository_url: https://github.com/ASaiM/galaxytools/tree/master/tools/group_humann2_uniref_abundances_to_GO
