categories: 
  - Tool Dependency Packages
description: "Contains a tool dependency definition that downloads and compiles version 0.4.1 of python patsy package"
name: package_python_2_7_patsy_0_4_1
owner: bebatut
remote_repository_url: https://github.com/ASaiM/galaxytools/tree/master/packages/package_python_2_7_patsy_0_4_1
