categories: 
  - Metagenomics
long_description: HUMAnN2 for functionally profiling metagenomes and metatranscriptomes at species-level resolution
description: Profilte 
name: humann2
owner: bebatut
remote_repository_url: https://github.com/ASaiM/galaxytools/tree/master/tools/humann2/
homepage_url: http://huttenhower.sph.harvard.edu/humann2
