categories: 
  - Tool Dependency Packages
description: "Contains a tool dependency definition that downloads and compiles version 0.1.4 of python fisher package"
name: package_python_2_7_fisher_0_1_4
owner: bebatut
remote_repository_url: https://github.com/ASaiM/galaxytools/tree/master/packages/package_python_2_7_fisher_0_1_4
