categories: 
  - Metagenomics
description: export2graphlan is a conversion software tool for producing both annotation and tree file for GraPhlAn
homepage_url: https://bitbucket.org/CibioCM/export2graphlan/overview
name: export2graphlan
owner: bebatut
remote_repository_url: https://github.com/ASaiM/galaxytools/tree/master/tools/export2graphlan/
