categories: 
  - Tool Dependency Packages
description: "Contains a tool dependency definition that downloads and compiles version 0.8.5 of python XlsxWriter package"
name: package_python_2_7_xlsxwriter_0_8_5
owner: bebatut
remote_repository_url: https://github.com/ASaiM/galaxytools/tree/master/packages/package_python_2_7_xlsxwriter_0_8_5
