categories: 
  - Fasta Manipulation
description: Format CD hit output
name: format_cd_hit_output
owner: bebatut
remote_repository_url: https://github.com/ASaiM/galaxytools/tree/master/tools/format_cd_hit_output/
