categories: 
  - Tool Dependency Packages
description: "Contains a tool dependency definition that downloads and installs version 1.20.0 of the getopt R library"
name: package_r_3_2_1_getopt_1_20_0
owner: bebatut
remote_repository_url: https://github.com/ASaiM/galaxytools/tree/master/packages/package_r_3_2_1_getopt_1_20_0
