categories: 
  - Tool Dependency Packages
description: "Contains a tool dependency definition that downloads and compiles version 3.2 of python wget package"
name: package_python_2_7_wget_3_2
owner: bebatut
remote_repository_url: https://github.com/ASaiM/galaxytools/tree/master/packages/package_python_2_7_wget_3_2
