categories: [Fastq Manipulation,Metagenomics]
description: PRINSEQ is a tool for easy and rapid quality control and data processing
  of metagenomic and metatranscriptomic datasets
homepage_url: http://prinseq.sourceforge.net/manual.html
name: prinseq
owner: bebatut
remote_repository_url: https://github.com/ASaiM/galaxytools/tree/master/tools/prinseq/
